In [90]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np
sns.set_style("darkgrid")
import math

In [91]:
data_path = "data/"
places = pd.read_csv(data_path + "places_final_NLP.csv", sep=",")
reviews = pd.read_csv(data_path + "reviews_final.csv", sep=",")

In [92]:
places.head()

,gPlusPlaceId,name,price,lat,lon,city,address,Grid,category
0,101742583391038750118,Carpo London,2.0,51.509499,-0.135762,London,"16 Piccadilly, London W1J 0DE, United Kingdom",L159,Retail
1,100574642292837870712,Premium Cars,NaN,51.514637,-0.064980,London,"10 Commercial Road Premium Cars First Floor, S...",L186,Other
2,105185983265572241970,eSpares Ltd,2.0,51.479416,-0.179209,London,"Chelsea Wharf, 15 Lots Rd, London, Chelsea SW1...",L40,Wholesale
3,104500852703501308358,Superdrug,NaN,51.494537,-0.145769,London,"Unit 35, Victoria Railway Station, London SW1V...",L101,Retail
4,107519298595557659572,Kura,2.0,51.502122,-0.163029,London,"3-4 Park Close, London SW1X 7PQ, United Kingdom",L137,Restaurant

In [272]:
Chelsea=np.where(places['address'].str.contains("E 53rd")==True)[0]

In [273]:
Chelsea

array([14275, 14441, 14619, 15074, 15403, 15879, 16409, 16431, 16579,
       16633, 17609, 18384, 18574, 18631, 19212, 19416, 19698, 19722,
       19730, 19852, 19997, 20414, 21687, 22137, 22782, 22906, 23153,
       23617, 24152, 24285, 24362, 24522, 24763, 26114, 26567, 27086,
       28610, 28770, 29109, 29135])

In [275]:
places.iloc[Chelsea, :]

,gPlusPlaceId,name,price,lat,lon,city,address,Grid,category
14275,103870272192897447430,Birdcamp,NaN,40.756205,-73.966023,New York,"330 E 53rd St, Manhattan, NY 10022",NY127,Other
14441,105322697020812882172,Mason's Tennis Mart,3.0,40.759265,-73.973492,New York,"56 E 53rd St, New York, NY 10022",NY126,Other
14619,100150761303772841594,Radicchio Pasta and Risotto,2.0,40.757239,-73.968029,New York,"235 E 53rd St, New York, NY 10022",NY127,Restaurant
15074,112402422428022835573,Le Pain Quotidien,2.0,40.760254,-73.975115,New York,"7 E 53rd St, New York, NY 10022",NY144,Wholesale
15403,105157169806024816960,Brick Lane Curry House,2.0,40.757330,-73.967902,New York,"235 E 53rd St # 1, New York, NY 10022",NY127,Restaurant
15879,107172332461115479869,Little Thai Kitchen,2.0,40.757235,-73.968093,New York,"231 E 53rd St, New York, NY 10022",NY127,Restaurant
16409,108013703039597555138,Newel,3.0,40.755307,-73.963532,New York,"425 E 53rd St, New York, NY 10022",NY128,Retail
16431,106431782820267132017,Jukai New York,3.0,40.757198,-73.968002,New York,"237 E 53rd St, New York, NY 10022",NY127,Restaurant
16579,112988574399651795496,Ah Chihuahua,2.0,40.756149,-73.965988,New York,"330 E 53rd St, New York, NY 10022",NY127,Restaurant
16633,113486671334444562021,OBAO,2.0,40.757122,-73.968566,New York,"222 E 53rd St #1, New York, NY 10022",NY127,Restaurant
17609,105721496821543968849,Solera Restaurant,3.0,40.757280,-73.968812,New York,"216 E 53rd St, New York, NY 10022",NY127,Restaurant
18384,117321280952706535768,Burger Heaven,2.0,40.760274,-73.974905,New York,"9 E 53rd St, New York, NY 10022",NY144,Restaurant
18574,110117414880511986551,Parnell's,2.0,40.755957,-73.965309,New York,"350 E 53rd St #1, New York, NY 10022",NY127,Restaurant
18631,110574637710496186564,Frederick Wildman & Sons Ltd,NaN,40.756649,-73.966511,New York,"307 E 53rd St # 3, New York, NY 10022",NY127,Wholesale
19212,114435389550266172172,Hillstone,3.0,40.758089,-73.969356,New York,"153 E 53rd St, New York, NY 10022",NY126,Restaurant
19416,109013160029810299395,Memorial Sloan Kettering,NaN,40.757748,-73.969757,New York,"160 E 53rd St, New York, NY 10022",NY126,Other
19698,102164546310112969799,Hot Kitchen,NaN,40.757013,-73.967489,New York,"251 E 53rd St, New York, NY 10022",NY127,Restaurant
19722,104957648923202992582,Valbella,3.0,40.759986,-73.975285,New York,"11 E 53rd St, Manhattan, NY 10022",NY144,Restaurant
19730,112151499773767644272,The Kati Roll Company,1.0,40.757334,-73.968139,New York,"229 E 53rd St, New York, NY 10022",NY127,Restaurant
19852,104281412053548991369,Rain Thai Restaurant,2.0,40.757294,-73.968674,New York,"220 E 53rd St, New York, NY 10022",NY127,Restaurant
19997,111946843996380352170,24 Hour Fitness,3.0,40.758161,-73.970069,New York,"153 E 53rd St, New York, NY 10022",NY126,Bar
20414,101960698868738726988,Blake & Todd,1.0,40.759178,-73.973649,New York,"52 E 53rd St, New York, NY 10022",NY125,Restaurant
21687,101991998373329416865,Lucky Cat,2.0,40.757055,-73.968225,New York,"232 E 53rd St, New York, NY 10022",NY127,Restaurant
22137,112493379982591424594,Mariachi's,2.0,40.757330,-73.967902,New York,"235 E 53rd St #2003, New York, NY 10022",NY127,Restaurant
22782,116319660456941320285,Brasserie,3.0,40.758623,-73.972032,New York,"100 E 53rd St, New York, NY 10022",NY126,Restaurant
22906,100801070914766203503,Luna Piena Restaurant,3.0,40.757126,-73.967738,New York,"243 E 53rd St, New York, NY 10022",NY127,Restaurant
23153,106389022793777332672,psychic in new york city,2.0,40.756652,-73.966664,New York,"303 E 53rd St #3, New York City, NY 10022",NY127,Other
23617,103597632700228575637,Peking Duck House,2.0,40.757025,-73.968044,New York,"236 E 53rd St, Manhattan, NY 10022",NY127,Restaurant
24152,116246087750241937851,Manish,NaN,40.757236,-73.968215,New York,"231 E 53rd St # 2, New York, NY 10022",NY127,Service
24285,113686486956415521791,Hudson Malone,NaN,40.757298,-73.968689,New York,"218 E 53rd St, New York, NY 10022",NY127,Restaurant
24362,109525215636713324690,Pounders Hawaiian Island Grill,2.0,40.757231,-73.968083,New York,"231 E 53rd St, New York, NY 10022",NY127,Restaurant
24522,116158642634225227690,Al Bustan,3.0,40.756438,-73.966209,New York,"319 E 53rd St, New York, NY 10022",NY127,Restaurant
24763,112541480417095886056,Terry May Concept Flowers,3.0,40.758440,-73.970443,New York,"153 E 53rd St, New York, NY 10022",NY126,Retail
26114,116959928896933040743,Ariyoshi,2.0,40.757159,-73.968331,New York,"226 E 53rd St, New York, NY 10022",NY127,Restaurant
26567,103569911265451732331,La Gioconda,2.0,40.757159,-73.968331,New York,"226 E 53rd St, Manhattan, NY 10022",NY127,Restaurant
27086,105800255155507722214,Cello Wine Bar,2.0,40.757171,-73.967568,New York,"229 E 53rd St, New York, NY 10022",NY127,Restaurant
28610,117504179627127474775,Marrakesh,1.0,40.757238,-73.967966,New York,"235 E 53rd St #2-3, New York, NY 10022",NY127,Restaurant
28770,101280977830882821486,Shafer Plastic Surgery,2.0,40.759915,-73.975212,New York,"10 E 53rd St, New York, NY 10022",NY144,Health
29109,112489246768024867017,Central Park Oral Surgery: Mark Andrei DDS,2.0,40.759480,-73.973929,New York,"515 Madison Avenue, 28th Floor, Entrance, E 53...",NY144,Health
29135,109931566675889714794,Prestige Barber Shop,2.0,40.757161,-73.967913,New York,"237 E 53rd St, New York, NY 10022",NY127,Bar

In [240]:
braseri=np.where(reviews['gPlusPlaceId']=='106861653242718638090')[0]

In [241]:
reviews.iloc[braseri, :]

,rating,reviewerName,reviewText,gPlusPlaceId,gPlusUserId,reviewTextClean,posReviewPercent,negReviewPercent,midReviewPercent
23228,5.0,Flor Calderon,NaN,106861653242718638090,101644904461538084503,NaN,NaN,NaN,NaN
28408,3.0,adame belay,I love chuckie cheese. If you want to have a g...,106861653242718638090,102006720155835180642,love chuckie cheese want good time family chil...,0.261,0.000,0.739
53960,2.0,Rachel del valle,This is one if the worst..disgusting places to...,106861653242718638090,103807420836975726448,one worst disgusting place go half machine rid...,0.023,0.163,0.814
64099,1.0,Isaac Nelson,I Agree With Everyone! That Location Is The Wo...,106861653242718638090,104590908416108922002,agree everyone location worst,0.176,0.330,0.494
70839,1.0,Gavin Jackson,My first and last time at chucky e cheese. Lik...,106861653242718638090,105055698331513684431,first last time chucky e cheese like madhouse ...,0.098,0.217,0.685
112313,4.0,aisha bilal,The food is good .fridays is the best and the ...,106861653242718638090,108064250661400790334,food good best game kid grate fun,0.380,0.000,0.620
115466,2.0,Hendrix Moses,The absolute worst Chuck E. Cheese I've ever b...,106861653242718638090,108274744990329830884,absolute worst chuck cheese ever personally st...,0.000,0.266,0.734
130181,2.0,Samantha Weddington,I will NEVER EVER take my family here again. I...,106861653242718638090,109171462640241055807,never ever take family surprised completely ho...,0.071,0.208,0.721
137240,1.0,Miguel Caraballo,I hate Chuck E Cheese and this location made m...,106861653242718638090,109688342995276708435,hate chuck e cheese location made hate ot even...,0.000,0.253,0.747
140604,4.0,Ali Hafnawi,NaN,106861653242718638090,109925855062565006810,NaN,NaN,NaN,NaN
157582,4.0,Metah Fore Genome,"loud, but what do you expect, its for kids lol",106861653242718638090,111123962845225755954,loud expect kid lol,0.291,0.000,0.709
186787,2.0,Kylie Geffner,great for oversized people. cheap and poor wua...,106861653242718638090,113316068935489990218,great oversized people cheap poor real authent...,0.214,0.161,0.625
192777,5.0,jah spencer,why are you people talking about chuck e chees...,106861653242718638090,113725461933429531989,people talking chuck e cheese love everybody love,0.375,0.000,0.625
206165,2.0,robert berg,absolutely disgusting experience.... horrible ...,106861653242718638090,114703524405243892941,absolutely disgusting experience horrible surr...,0.032,0.263,0.705
212743,4.0,Hector Craig,NaN,106861653242718638090,115125695090854934644,NaN,NaN,NaN,NaN
234081,2.0,Yoav Erez,Came pretty early on Friday and the place was ...,106861653242718638090,116732735237059856250,came pretty early friday place wa pretty empty...,0.127,0.070,0.803
237416,2.0,Ariel Castro,Needs improvment,106861653242718638090,116993636775111476242,need improvment,0.000,0.000,1.000
241525,4.0,Luisdaniel Sanchez,NaN,106861653242718638090,117233798831130236204,NaN,NaN,NaN,NaN